[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
build_type = release
build_unflags =
    -std=gnu++11
    -Og
    -g3
build_flags =
    -std=gnu++17
    -Os
    -g0
    -DNDEBUG
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
    -DWIFI_SSID=\"YOUR_SSID\"
    -DWIFI_PASSWORD=\"YOUR_PASSWORD\"
    -DAP_SSID=\"HomeHub-Setup\"
    -DAP_PASSWORD=\"homehub123\"
    -DOTA_HOSTNAME=\"home-hub\"
    -DOTA_PASSWORD=\"homehub\"
lib_ldf_mode = deep+
board_build.partitions = huge_app.csv

