[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600
build_type = debug
build_unflags =
    -std=gnu++11
build_flags =
    -std=gnu++17
lib_ldf_mode = deep+

